### ISSUE TITLE
Cannot find module './test.js'

### ISSUE THREAD

**Issue by aladdin-add** [lydell/eslump#7]
```bash
$ eslump ./test.js output
```
it reports `Cannot find module './test.js'` -- since`./test.js` is a file, not a package.

I can make a repo to reproduce later(if needed).

background: I was trying to use it in [cherow](https://github.com/cherow/cherow).

**Comment by lydell** [comment]
Did you create `./test.js` first?

**Comment by aladdin-add** [comment]
yes, I did. here is a repro: https://github.com/Aladdin-ADD/eslump-issue7

![image](https://user-images.githubusercontent.com/13050025/49327137-2b97c180-f598-11e8-8ffb-371550589a8b.png)

**Comment by lydell** [comment]
Thanks. First, you need the `./` since it is a local file and not a package in `node_modules`. But even with `eslump ./cherow.js output` I got the error. I have almost exclusively run the CLI directly in the eslump repo so I haven’t noticed :) I think the issue is that the CLI tries to `require("./cherow.js")` relative to itself, not relative to CWD.

**Comment by lydell** [comment]
For now, you can clone this repo and run the bundled cherow example. It might be a bit outdated, though.

**Comment by lydell** [comment]
Fixed in v2.0.0
